### ISSUE TITLE
I can't run 'sampledata = as.data.frame(cbind(data[j,], t(C)))' in EstimateS.R

### ISSUE THREAD

**Issue by shimw6828** [elolab/Rodeo#2]
I can't run 'sampledata = as.data.frame(cbind(data[j,], t(C)))' in EstimateS.R. Should it be "cbind(t(data[j,]), t(C))"？

**Comment by MKJaakkola** [comment]
Dear shimw6828, 

Thank you for your feedback. I think that the original version was fine for matrices, but caused issues with data frames. I have added as.numeric to data[j,], which should fix the issue for data frames as it creates a column vector. Please let me know, if the issue remains.
